### ISSUE TITLE
1st To-Do List to get the first page of website running

### ISSUE THREAD

**Issue by Dsantra92** [Sigma-eX/ML-Gamify#2]
- [ ] Add proper Requirements.txt @justAcoderguy <br> You can get it by `pip freeze`

- [ ] Update the docker(GitPod) for node specs. @Dsantra92 

- [ ]  Upload the 1st Page of the website and get the first basic functionalities. @aritropc
